#!/usr/bin/env bash

git diff --cached --name-only | while read FILE; do
if [[ "$FILE" =~ ^.+(_spec.rb)$ ]]; then
  if [[ -f $FILE ]]; then
    content=$(<"$FILE")
    if [[ $(echo "$content" | ag "focus" | ag "true") ]]; then
      echo -e "\e[1;31m\tAborting commit due to focus: true" >&2
      exit 1
    fi
  fi
fi
done
